#!/bin/bash php
<?php

function line(string $line, ?string $level = null)
{
    echo match ($level) {
        'error' => "\033[31m[x] \033[0m".$line.PHP_EOL,
        'success' => "\033[32m[+] \033[0m".$line.PHP_EOL,
        'warning' => "\033[33m[!] \033[0m".$line.PHP_EOL,
        'info' => "\033[36m[i] \033[0m".$line.PHP_EOL,
        default => $line.PHP_EOL,
    };

}

function info(string $line)
{
    line($line, 'info');
}

function success(string $line)
{
    line($line, 'success');
}

function error(string $line, bool $shouldExit = true, int $exitCode = 0)
{
    line($line, 'error');
    if($shouldExit){
      exit($exitCode);
    }
}

function warning(string $line)
{
    line($line, 'warning');
}

function ask(string $question, string $default = '')
{
    $answer = readline('>>  '.$question.($default ? " (Default: {$default}) : " : " : "));

    return !$answer ? $default : $answer;
}

function choose(string $question, array $options, string $default = '')
{
  $answer = ask($question."\n\t- ".implode("\n\t- ",$options)."\n\t ",$default);

  if(!array_key_exists($answer, array_flip($options))) {
    error('Invalid option', false);
    return choose($question,$options,$default);
  }

  return $answer;
}

function confirm(string $question, bool $default = true)
{
    $confirmation = ask($question.' ('.($default ? "\033[33mY\033[0m/n" : "y/\033[33mN\033[0m").") : ");


    return match (strtolower($confirmation ?? '')) {
        'y', 'yes', '1' => true,
        'n', 'no', '0' => false,
        default => $default
    };
}

function run(string $command): string
{
    return trim((string) shell_exec($command));
}

$defaultAuthor = run('git config user.name');

function help()
{
    global $defaultAuthor;
    line('Usage: php package <package-name> [options]');
    line('Options:');
    line("  author\tAuthor Name\t\teg: php package <package-name> author=\"{$defaultAuthor}\"");
}

function configurePackage(?string $packageName, array $options = [])
{
    global $defaultAuthor;
    line('Configuring package: '.$packageName);
    $decisions = [
        '{php_version}' => '^'.choose('PHP version', ['8.0','8.1','8.2'], '8.1'),
        '{vendor}' => strpos($packageName, '/') ? explode('/', $packageName)[0] : ask('Vendor name'),
        '{package_name}' => $packageName,
        '{namespace}' => ask('Package namespace'),
        '{description}' => ask('Package description'),
        '{author}' => ask('Package author', $defaultAuthor),
    ];

    $files = glob(__DIR__.'/*');

    foreach ($files as $file) {
        if (is_dir($file) || $file === __FILE__) {
            continue;
        }
        $contents = file_get_contents($file);
        foreach ($decisions as $key => $value) {
            $contents = str_replace($key, $value, $contents);
        }
        file_put_contents($file, $contents);
    }

    if(!is_dir(__DIR__.'/.git') && confirm('Do you want to initialize git repository?')) {
        run('git init');
        run('git add .');
        run('git commit -m "Initial commit"');
    }

    run('composer require illuminate/support');
    run('composer require phpstan/phpstan --dev');
    run('composer require pestphp/pest --dev');

    if(confirm('Do you want to install dependencies?')) {
        run('composer install');
    }

    if(confirm('Does the script destroy itself?')) {
        unlink(__FILE__);
    }
}


if (!($packageName = $argv[1] ?? null)) {
    error('Package name must be provided');
}
unset($argv[0], $argv[1]);
$argv = array_values($argv);
parse_str(implode('&', $argv), $options);

switch ($packageName) {
    case 'help':
        help();
        break;
    default:
        configurePackage($packageName, $options);
        break;
}

